#!/usr/bin/env python3
"""Regenerate src/config/qwerty_base.inc -- the key list behind `"base": "qwerty"`.

    scripts/gen-qwerty.py            # rewrite the .inc in place
    scripts/gen-qwerty.py --list     # print the names, one per line

`"base": "qwerty"` makes every one of these keys type itself unless the config
says otherwise, so a config only has to mention what it changes."""
import os
import sys

ROWS = [
    "esc f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 sysrq scrolllock pause",
    "grave 1 2 3 4 5 6 7 8 9 0 minus equal backspace insert home pageup",
    "tab q w e r t y u i o p leftbrace rightbrace backslash delete end pagedown",
    "capslock a s d f g h j k l semicolon apostrophe enter",
    "leftshift z x c v b n m comma dot slash rightshift up",
    "leftctrl leftmeta leftalt space rightalt rightmeta compose rightctrl left down right",
    "numlock kpslash kpasterisk kpminus kp7 kp8 kp9 kpplus kp4 kp5 kp6 kp1 kp2 kp3 kpenter kp0 kpdot",
    "mute volumedown volumeup playpause nextsong previoussong brightnessdown brightnessup",
]

keys = [k for row in ROWS for k in row.split()]

if "--list" in sys.argv:
    print("\n".join(keys))
    sys.exit(0)

out = os.path.join(os.path.dirname(__file__), "..", "src", "config", "qwerty_base.inc")
with open(out, "w") as f:
    f.write("/* Generated by scripts/gen-qwerty.py -- do not edit. */\n")
    for row in ROWS:
        f.write("\t" + " ".join('"%s",' % k for k in row.split()) + "\n")
print("wrote %s (%d keys)" % (os.path.normpath(out), len(keys)), file=sys.stderr)
